com::example::test::R::attr
final int org.opencv.R.attr.camera_id
final int org.opencv.R.attr.show_fps
final boolean com.example.test.BuildConfig.DEBUG
final int com.example.test.R.color.transparent
final String com.camera.view.activity.ColorBlobDetectionActivity.TAG
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.ColorBlobDetectionActivity, com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame, com.camera.view.activity.ColorBlobDetectionActivity.onCreate, com.camera.view.activity.ColorBlobDetectionActivity.onCreateOptionsMenu, com.camera.view.activity.ColorBlobDetectionActivity.onOptionsItemSelected, com.camera.view.activity.ColorBlobDetectionActivity.onTouch.
final int com.camera.view.activity.ColorBlobDetectionActivity.ACCUMULATOR_THRESHOLD
final int com.camera.view.activity.ColorBlobDetectionActivity.MINLINELENGTH
final int com.camera.view.activity.ColorBlobDetectionActivity.MAXLINEGAP
final int com.camera.view.activity.ColorBlobDetectionActivity.HYSTERESIS_THRESHOLD1
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame.
final int com.camera.view.activity.ColorBlobDetectionActivity.HYSTERESIS_THRESHOLD2
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame.
final int com.camera.view.activity.ColorBlobDetectionActivity.HOUGH_LINE_COUNT
boolean com.camera.view.activity.ColorBlobDetectionActivity.mIsColorSelected
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame, com.camera.view.activity.ColorBlobDetectionActivity.onTouch.
boolean com.camera.view.activity.ColorBlobDetectionActivity.getPoints
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame, com.camera.view.activity.ColorBlobDetectionActivity.onOptionsItemSelected.
boolean com.camera.view.activity.ColorBlobDetectionActivity.haveCalculated
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame.
Mat com.camera.view.activity.ColorBlobDetectionActivity.mRgba
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame, com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted, com.camera.view.activity.ColorBlobDetectionActivity.onOptionsItemSelected.
Mat com.camera.view.activity.ColorBlobDetectionActivity.mGray
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame, com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Mat com.camera.view.activity.ColorBlobDetectionActivity.lines
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame, com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Mat com.camera.view.activity.ColorBlobDetectionActivity.edges
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame, com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Scalar com.camera.view.activity.ColorBlobDetectionActivity.mBlobColorRgba
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted, com.camera.view.activity.ColorBlobDetectionActivity.onTouch.
Scalar com.camera.view.activity.ColorBlobDetectionActivity.mBlobColorHsv
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted, com.camera.view.activity.ColorBlobDetectionActivity.onTouch.
ColorBlobDetector com.camera.view.activity.ColorBlobDetectionActivity.mDetector
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Mat com.camera.view.activity.ColorBlobDetectionActivity.mSpectrum
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted, com.camera.view.activity.ColorBlobDetectionActivity.onTouch.
Size com.camera.view.activity.ColorBlobDetectionActivity.SPECTRUM_SIZE
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted, com.camera.view.activity.ColorBlobDetectionActivity.onTouch.
Scalar com.camera.view.activity.ColorBlobDetectionActivity.CONTOUR_COLOR
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
double com.camera.view.activity.ColorBlobDetectionActivity.minX
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame.
Mat com.camera.view.activity.ColorBlobDetectionActivity.mPyrDownMat
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Mat com.camera.view.activity.ColorBlobDetectionActivity.mHsvMat
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Mat com.camera.view.activity.ColorBlobDetectionActivity.mMask
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Mat com.camera.view.activity.ColorBlobDetectionActivity.mDilatedMask
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Mat com.camera.view.activity.ColorBlobDetectionActivity.mHierarchy
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame, com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted.
Scalar com.camera.view.activity.ColorBlobDetectionActivity.mLowerBound
Scalar com.camera.view.activity.ColorBlobDetectionActivity.mUpperBound
MenuItem com.camera.view.activity.ColorBlobDetectionActivity.saveImage
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCreateOptionsMenu, com.camera.view.activity.ColorBlobDetectionActivity.onOptionsItemSelected.
Tutorial3View com.camera.view.activity.ColorBlobDetectionActivity.mOpenCvCameraView
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCreate, com.camera.view.activity.ColorBlobDetectionActivity.onDestroy, com.camera.view.activity.ColorBlobDetectionActivity.onPause.
BaseLoaderCallback com.camera.view.activity.ColorBlobDetectionActivity.mLoaderCallback
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onResume.
double com.camera.view.activity.ColorBlobDetectionActivity.minY
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame.
double com.camera.view.activity.ColorBlobDetectionActivity.maxX
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame.
double com.camera.view.activity.ColorBlobDetectionActivity.maxY
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame.
com.camera.view.activity.ColorBlobDetectionActivity.ColorBlobDetectionActivity()
References com.camera.view.activity.ColorBlobDetectionActivity.TAG.
void com.camera.view.activity.ColorBlobDetectionActivity.onCreate(Bundle savedInstanceState)
Called when the activity is first created.
References com.camera.view.activity.ColorBlobDetectionActivity.mOpenCvCameraView, com.camera.view.activity.ColorBlobDetectionActivity.TAG.
void com.camera.view.activity.ColorBlobDetectionActivity.onPause()
References com.camera.view.activity.ColorBlobDetectionActivity.mOpenCvCameraView.
void com.camera.view.activity.ColorBlobDetectionActivity.onResume()
References com.camera.view.activity.ColorBlobDetectionActivity.mLoaderCallback.
void com.camera.view.activity.ColorBlobDetectionActivity.onDestroy()
References com.camera.view.activity.ColorBlobDetectionActivity.mOpenCvCameraView.
boolean com.camera.view.activity.ColorBlobDetectionActivity.onCreateOptionsMenu(Menu menu)
References com.camera.view.activity.ColorBlobDetectionActivity.saveImage, com.camera.view.activity.ColorBlobDetectionActivity.TAG.
boolean com.camera.view.activity.ColorBlobDetectionActivity.onOptionsItemSelected(MenuItem item)
References com.camera.view.activity.ColorBlobDetectionActivity.getPoints, com.camera.view.activity.ColorBlobDetectionActivity.mRgba, com.camera.view.activity.ColorBlobDetectionActivity.saveImage, com.camera.view.activity.ColorBlobDetectionActivity.TAG.
void com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStarted(int width, int height)
References com.camera.view.activity.ColorBlobDetectionActivity.CONTOUR_COLOR, com.camera.view.activity.ColorBlobDetectionActivity.edges, com.camera.view.activity.ColorBlobDetectionActivity.lines, com.camera.view.activity.ColorBlobDetectionActivity.mBlobColorHsv, com.camera.view.activity.ColorBlobDetectionActivity.mBlobColorRgba, com.camera.view.activity.ColorBlobDetectionActivity.mDetector, com.camera.view.activity.ColorBlobDetectionActivity.mDilatedMask, com.camera.view.activity.ColorBlobDetectionActivity.mGray, com.camera.view.activity.ColorBlobDetectionActivity.mHierarchy, com.camera.view.activity.ColorBlobDetectionActivity.mHsvMat, com.camera.view.activity.ColorBlobDetectionActivity.mMask, com.camera.view.activity.ColorBlobDetectionActivity.mPyrDownMat, com.camera.view.activity.ColorBlobDetectionActivity.mRgba, com.camera.view.activity.ColorBlobDetectionActivity.mSpectrum, com.camera.view.activity.ColorBlobDetectionActivity.SPECTRUM_SIZE.
void com.camera.view.activity.ColorBlobDetectionActivity.onCameraViewStopped()
boolean com.camera.view.activity.ColorBlobDetectionActivity.onTouch(View v, MotionEvent event)
References com.camera.view.activity.ColorBlobDetectionActivity.converScalarHsv2Rgba, com.camera.view.activity.ColorBlobDetectionActivity.mBlobColorHsv, com.camera.view.activity.ColorBlobDetectionActivity.mBlobColorRgba, com.camera.view.activity.ColorBlobDetectionActivity.mIsColorSelected, com.camera.view.activity.ColorBlobDetectionActivity.mSpectrum, com.camera.view.activity.ColorBlobDetectionActivity.SPECTRUM_SIZE, com.camera.view.activity.ColorBlobDetectionActivity.TAG.
Mat com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame(CvCameraViewFrame inputFrame)
References com.camera.view.activity.ColorBlobDetectionActivity.edges, com.camera.control.detector.ColorBlobDetector.findMaxContourIdx, com.camera.view.activity.ColorBlobDetectionActivity.getPoints, com.camera.view.activity.ColorBlobDetectionActivity.haveCalculated, com.camera.view.activity.ColorBlobDetectionActivity.HYSTERESIS_THRESHOLD1, com.camera.view.activity.ColorBlobDetectionActivity.HYSTERESIS_THRESHOLD2, com.camera.view.activity.ColorBlobDetectionActivity.lines, com.camera.view.activity.ColorBlobDetectionActivity.maxX, com.camera.view.activity.ColorBlobDetectionActivity.maxY, com.camera.view.activity.ColorBlobDetectionActivity.mGray, com.camera.view.activity.ColorBlobDetectionActivity.mHierarchy, com.camera.view.activity.ColorBlobDetectionActivity.minX, com.camera.view.activity.ColorBlobDetectionActivity.minY, com.camera.view.activity.ColorBlobDetectionActivity.mIsColorSelected, com.camera.view.activity.ColorBlobDetectionActivity.mRgba, com.camera.view.activity.ColorBlobDetectionActivity.TAG.
Scalar com.camera.view.activity.ColorBlobDetectionActivity.converScalarHsv2Rgba(Scalar hsvColor)
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onTouch.
Scalar com.camera.control.detector.ColorBlobDetector.mLowerBound
Referenced by com.camera.control.detector.ColorBlobDetector.process.
Scalar com.camera.control.detector.ColorBlobDetector.mUpperBound
Referenced by com.camera.control.detector.ColorBlobDetector.process.
Scalar com.camera.control.detector.ColorBlobDetector.mColorRadius
Referenced by com.camera.control.detector.ColorBlobDetector.setColorRadius, com.camera.control.detector.ColorBlobDetector.setHsvColor.
Mat com.camera.control.detector.ColorBlobDetector.mSpectrum
Referenced by com.camera.control.detector.ColorBlobDetector.getSpectrum, com.camera.control.detector.ColorBlobDetector.setHsvColor.
List<MatOfPoint> com.camera.control.detector.ColorBlobDetector.mContours
Referenced by com.camera.control.detector.ColorBlobDetector.getContours.
MatOfPoint com.camera.control.detector.ColorBlobDetector.maxContour
double com.camera.control.detector.ColorBlobDetector.mMinContourArea
Referenced by com.camera.control.detector.ColorBlobDetector.process, com.camera.control.detector.ColorBlobDetector.setMinContourArea.
Mat com.camera.control.detector.ColorBlobDetector.mPyrDownMat
Referenced by com.camera.control.detector.ColorBlobDetector.process.
Mat com.camera.control.detector.ColorBlobDetector.mHsvMat
Referenced by com.camera.control.detector.ColorBlobDetector.process.
Mat com.camera.control.detector.ColorBlobDetector.mMask
Referenced by com.camera.control.detector.ColorBlobDetector.process.
Mat com.camera.control.detector.ColorBlobDetector.mDilatedMask
Referenced by com.camera.control.detector.ColorBlobDetector.process.
Mat com.camera.control.detector.ColorBlobDetector.mHierarchy
Referenced by com.camera.control.detector.ColorBlobDetector.process.
void com.camera.control.detector.ColorBlobDetector.setColorRadius(Scalar radius)
References com.camera.control.detector.ColorBlobDetector.mColorRadius.
void com.camera.control.detector.ColorBlobDetector.setHsvColor(Scalar hsvColor)
References com.camera.control.detector.ColorBlobDetector.mColorRadius, com.camera.control.detector.ColorBlobDetector.mSpectrum.
Mat com.camera.control.detector.ColorBlobDetector.getSpectrum()
References com.camera.control.detector.ColorBlobDetector.mSpectrum.
void com.camera.control.detector.ColorBlobDetector.setMinContourArea(double area)
References com.camera.control.detector.ColorBlobDetector.mMinContourArea.
void com.camera.control.detector.ColorBlobDetector.process(Mat rgbaImage)
References com.camera.control.detector.ColorBlobDetector.mDilatedMask, com.camera.control.detector.ColorBlobDetector.mHierarchy, com.camera.control.detector.ColorBlobDetector.mHsvMat, com.camera.control.detector.ColorBlobDetector.mLowerBound, com.camera.control.detector.ColorBlobDetector.mMask, com.camera.control.detector.ColorBlobDetector.mMinContourArea, com.camera.control.detector.ColorBlobDetector.mPyrDownMat, com.camera.control.detector.ColorBlobDetector.mUpperBound.
List<MatOfPoint> com.camera.control.detector.ColorBlobDetector.getContours()
References com.camera.control.detector.ColorBlobDetector.mContours.
static int com.camera.control.detector.ColorBlobDetector.findMaxContourIdx(List< MatOfPoint > contours)
Referenced by com.camera.view.activity.ColorBlobDetectionActivity.onCameraFrame.
final int com.example.test.R.dimen.activity_horizontal_margin
Default screen margins, per the Android Design guidelines.Customize dimensions originally defined in res/values/dimens.xml (such as screen margins) for sw720dp devices (e.g. 10" tablets) in landscape here.
final int com.example.test.R.dimen.activity_vertical_margin
final int com.example.test.R.drawable.ic_action_camera
final int com.example.test.R.drawable.ic_action_computer
final int com.example.test.R.drawable.ic_action_dial_pad
final int com.example.test.R.drawable.ic_action_directions
final int com.example.test.R.drawable.ic_action_photo
final int com.example.test.R.drawable.ic_action_place
final int com.example.test.R.drawable.ic_action_rotate_right
final int com.example.test.R.drawable.ic_action_storage
final int com.example.test.R.drawable.ic_action_volume_on
final int com.example.test.R.drawable.ic_launcher
Gallery com.camera.view.activity.GalleryActivity.gallery
Referenced by com.camera.view.activity.GalleryActivity.onCreate.
void com.camera.view.activity.GalleryActivity.onCreate(Bundle savedInstanceState)
References com.camera.view.activity.GalleryActivity.gallery.
final int com.example.test.R.id.action_settings
final int com.example.test.R.id.background
final int com.example.test.R.id.camer
final int com.example.test.R.id.color_blob_detection_activity_surface_view
final int com.example.test.R.id.container
final int com.example.test.R.id.file
final int com.example.test.R.id.gallery
final int com.example.test.R.id.iconBar
final int com.example.test.R.id.layout
final int com.example.test.R.id.load_model
final int com.example.test.R.id.mainView
final int com.example.test.R.id.mygallery
final int com.example.test.R.id.rotate
final int com.example.test.R.id.scale
final int com.example.test.R.id.switcher
final int com.example.test.R.id.three_diemension
final int com.example.test.R.id.translate
final int com.example.test.R.id.view3d
final int org.opencv.R.id.any
final int org.opencv.R.id.back
final int org.opencv.R.id.front
int [] com.camera.control.adapter.ImageAdapter.images
Referenced by com.camera.control.adapter.ImageAdapter.getView, com.camera.control.adapter.ImageAdapter.ImageAdapter.
Context com.camera.control.adapter.ImageAdapter.context
Referenced by com.camera.control.adapter.ImageAdapter.getView, com.camera.control.adapter.ImageAdapter.ImageAdapter.
com.camera.control.adapter.ImageAdapter.ImageAdapter(Context context, int[] images)
References com.camera.control.adapter.ImageAdapter.context, com.camera.control.adapter.ImageAdapter.images.
int com.camera.control.adapter.ImageAdapter.getCount()
Object com.camera.control.adapter.ImageAdapter.getItem(int position)
long com.camera.control.adapter.ImageAdapter.getItemId(int position)
View com.camera.control.adapter.ImageAdapter.getView(int position, View convertView, ViewGroup parent)
References com.camera.control.adapter.ImageAdapter.context, com.camera.control.adapter.ImageAdapter.images.
Context com.camera.view.activity.GalleryActivity.ImageAdapter.context
Referenced by com.camera.view.activity.GalleryActivity.ImageAdapter.getView, com.camera.view.activity.GalleryActivity.ImageAdapter.ImageAdapter.
List<Integer> com.camera.view.activity.GalleryActivity.ImageAdapter.imgList
List<Object> com.camera.view.activity.GalleryActivity.ImageAdapter.imgSizes
Referenced by com.camera.view.activity.GalleryActivity.ImageAdapter.getView.
com.camera.view.activity.GalleryActivity.ImageAdapter.ImageAdapter(Context context)
References com.camera.view.activity.GalleryActivity.ImageAdapter.context.
int com.camera.view.activity.GalleryActivity.ImageAdapter.getCount()
Object com.camera.view.activity.GalleryActivity.ImageAdapter.getItem(int position)
long com.camera.view.activity.GalleryActivity.ImageAdapter.getItemId(int position)
View com.camera.view.activity.GalleryActivity.ImageAdapter.getView(int position, View convertView, ViewGroup parent)
References com.camera.view.activity.GalleryActivity.ImageAdapter.context, com.camera.view.activity.GalleryActivity.ImageAdapter.imgSizes.
int com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.mGalleryItemBackground
Referenced by com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.getView, com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.ImageAdapter.
Context com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.mContext
Referenced by com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.getView, com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.ImageAdapter.
List<String> com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.lis
Referenced by com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.ImageAdapter.
com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.ImageAdapter(Context c, List< String > li)
References com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.lis, com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.mContext, com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.mGalleryItemBackground.
int com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.getCount()
Object com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.getItem(int position)
long com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.getItemId(int position)
View com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.getView(int position, View convertView, ViewGroup parent)
References com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.mContext, com.camera.view.activity.ImageSwitcherAndGalleryActivity.ImageAdapter.mGalleryItemBackground.
final int com.example.test.R.layout.activity_main
final int com.example.test.R.layout.color_blob_detection_surface_view
final int com.example.test.R.layout.fragment_main
final int com.example.test.R.layout.gallery
final int com.example.test.R.layout.main
final int com.example.test.R.layout.main_layout
final int com.example.test.R.layout.paper_detection_surface_view
final String com.camera.control.renderer.LessonTwoRenderer.TAG
Used for debug logs.
Referenced by com.camera.control.renderer.LessonTwoRenderer.compileShader, com.camera.control.renderer.LessonTwoRenderer.createAndLinkProgram.
float [] com.camera.control.renderer.LessonTwoRenderer.mModelMatrix
Store the model matrix. This matrix is used to move models from object space (where each model can be thought of being located at the center of the universe) to world space.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
float [] com.camera.control.renderer.LessonTwoRenderer.mViewMatrix
Store the view matrix. This can be thought of as our camera. This matrix transforms world space to eye space; it positions things relative to our eye.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawLight, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame, com.camera.control.renderer.LessonTwoRenderer.onSurfaceCreated.
float [] com.camera.control.renderer.LessonTwoRenderer.mProjectionMatrix
Store the projection matrix. This is used to project the scene onto a 2D viewport.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawLight, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onSurfaceChanged.
float [] com.camera.control.renderer.LessonTwoRenderer.mMVPMatrix
Allocate storage for the final combined matrix. This will be passed into the shader program.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawLight, com.camera.control.renderer.LessonTwoRenderer.drawTriangle.
float [] com.camera.control.renderer.LessonTwoRenderer.mLightModelMatrix
Stores a copy of the model matrix specifically for the light position.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawLight, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
final FloatBuffer com.camera.control.renderer.LessonTwoRenderer.mCubePositions
Store our model data in a float buffer.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.LessonTwoRenderer.
final FloatBuffer com.camera.control.renderer.LessonTwoRenderer.mCubeColors
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.LessonTwoRenderer.
final FloatBuffer com.camera.control.renderer.LessonTwoRenderer.mCubeNormals
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.LessonTwoRenderer.
int com.camera.control.renderer.LessonTwoRenderer.mMVPMatrixHandle
This will be used to pass in the transformation matrix.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
int com.camera.control.renderer.LessonTwoRenderer.mMVMatrixHandle
This will be used to pass in the modelview matrix.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
int com.camera.control.renderer.LessonTwoRenderer.mLightPosHandle
This will be used to pass in the light position.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
int com.camera.control.renderer.LessonTwoRenderer.mPositionHandle
This will be used to pass in model position information.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
int com.camera.control.renderer.LessonTwoRenderer.mColorHandle
This will be used to pass in model color information.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
int com.camera.control.renderer.LessonTwoRenderer.mNormalHandle
This will be used to pass in model normal information.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
final int com.camera.control.renderer.LessonTwoRenderer.mBytesPerFloat
How many bytes per float.
Referenced by com.camera.control.renderer.LessonTwoRenderer.LessonTwoRenderer.
final int com.camera.control.renderer.LessonTwoRenderer.mPositionDataSize
Size of the position data in elements.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle.
final int com.camera.control.renderer.LessonTwoRenderer.mColorDataSize
Size of the color data in elements.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle.
final int com.camera.control.renderer.LessonTwoRenderer.mNormalDataSize
Size of the normal data in elements.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle.
final float [] com.camera.control.renderer.LessonTwoRenderer.mLightPosInModelSpace
Used to hold a light centered on the origin in model space. We need a 4th coordinate so we can get translations to work when we multiply this by our transformation matrices.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawLight, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
final float [] com.camera.control.renderer.LessonTwoRenderer.mLightPosInWorldSpace
Used to hold the current position of the light in world space (after transformation via model matrix).
Referenced by com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
final float [] com.camera.control.renderer.LessonTwoRenderer.mLightPosInEyeSpace
Used to hold the transformed position of the light in eye space (after transformation via modelview matrix)
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawTriangle, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
int com.camera.control.renderer.LessonTwoRenderer.mPerVertexProgramHandle
This is a handle to our per-vertex cube shading program.
Referenced by com.camera.control.renderer.LessonTwoRenderer.onDrawFrame, com.camera.control.renderer.LessonTwoRenderer.onSurfaceCreated.
int com.camera.control.renderer.LessonTwoRenderer.mPointProgramHandle
This is a handle to our light point program.
Referenced by com.camera.control.renderer.LessonTwoRenderer.drawLight, com.camera.control.renderer.LessonTwoRenderer.onDrawFrame, com.camera.control.renderer.LessonTwoRenderer.onSurfaceCreated.
com.camera.control.renderer.LessonTwoRenderer.LessonTwoRenderer()
Initialize the model data.
References com.camera.control.renderer.LessonTwoRenderer.mBytesPerFloat, com.camera.control.renderer.LessonTwoRenderer.mCubeColors, com.camera.control.renderer.LessonTwoRenderer.mCubeNormals, com.camera.control.renderer.LessonTwoRenderer.mCubePositions.
void com.camera.control.renderer.LessonTwoRenderer.onSurfaceCreated(GL10 glUnused, EGLConfig config)
References com.camera.control.renderer.LessonTwoRenderer.compileShader, com.camera.control.renderer.LessonTwoRenderer.createAndLinkProgram, com.camera.control.renderer.LessonTwoRenderer.getFragmentShader, com.camera.control.renderer.LessonTwoRenderer.getVertexShader, com.camera.control.renderer.LessonTwoRenderer.mPerVertexProgramHandle, com.camera.control.renderer.LessonTwoRenderer.mPointProgramHandle, com.camera.control.renderer.LessonTwoRenderer.mViewMatrix.
void com.camera.control.renderer.LessonTwoRenderer.onSurfaceChanged(GL10 glUnused, int width, int height)
References com.camera.control.renderer.LessonTwoRenderer.mProjectionMatrix.
void com.camera.control.renderer.LessonTwoRenderer.onDrawFrame(GL10 glUnused)
References com.camera.control.renderer.LessonTwoRenderer.drawCube, com.camera.control.renderer.LessonTwoRenderer.drawLight, com.camera.control.renderer.LessonTwoRenderer.mColorHandle, com.camera.control.renderer.LessonTwoRenderer.mLightModelMatrix, com.camera.control.renderer.LessonTwoRenderer.mLightPosHandle, com.camera.control.renderer.LessonTwoRenderer.mLightPosInEyeSpace, com.camera.control.renderer.LessonTwoRenderer.mLightPosInModelSpace, com.camera.control.renderer.LessonTwoRenderer.mLightPosInWorldSpace, com.camera.control.renderer.LessonTwoRenderer.mModelMatrix, com.camera.control.renderer.LessonTwoRenderer.mMVMatrixHandle, com.camera.control.renderer.LessonTwoRenderer.mMVPMatrixHandle, com.camera.control.renderer.LessonTwoRenderer.mNormalHandle, com.camera.control.renderer.LessonTwoRenderer.mPerVertexProgramHandle, com.camera.control.renderer.LessonTwoRenderer.mPointProgramHandle, com.camera.control.renderer.LessonTwoRenderer.mPositionHandle, com.camera.control.renderer.LessonTwoRenderer.mViewMatrix.
String com.camera.control.renderer.LessonTwoRenderer.getVertexShader()
Referenced by com.camera.control.renderer.LessonTwoRenderer.onSurfaceCreated.
String com.camera.control.renderer.LessonTwoRenderer.getFragmentShader()
Referenced by com.camera.control.renderer.LessonTwoRenderer.onSurfaceCreated.
void com.camera.control.renderer.LessonTwoRenderer.drawCube()
Draws a cube.
References com.camera.control.renderer.LessonTwoRenderer.mColorDataSize, com.camera.control.renderer.LessonTwoRenderer.mColorHandle, com.camera.control.renderer.LessonTwoRenderer.mCubeColors, com.camera.control.renderer.LessonTwoRenderer.mCubeNormals, com.camera.control.renderer.LessonTwoRenderer.mCubePositions, com.camera.control.renderer.LessonTwoRenderer.mLightPosHandle, com.camera.control.renderer.LessonTwoRenderer.mLightPosInEyeSpace, com.camera.control.renderer.LessonTwoRenderer.mModelMatrix, com.camera.control.renderer.LessonTwoRenderer.mMVMatrixHandle, com.camera.control.renderer.LessonTwoRenderer.mMVPMatrix, com.camera.control.renderer.LessonTwoRenderer.mMVPMatrixHandle, com.camera.control.renderer.LessonTwoRenderer.mNormalDataSize, com.camera.control.renderer.LessonTwoRenderer.mNormalHandle, com.camera.control.renderer.LessonTwoRenderer.mPositionDataSize, com.camera.control.renderer.LessonTwoRenderer.mPositionHandle, com.camera.control.renderer.LessonTwoRenderer.mProjectionMatrix, com.camera.control.renderer.LessonTwoRenderer.mViewMatrix.
Referenced by com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
void com.camera.control.renderer.LessonTwoRenderer.drawTriangle()
References com.camera.control.renderer.LessonTwoRenderer.mColorDataSize, com.camera.control.renderer.LessonTwoRenderer.mColorHandle, com.camera.control.renderer.LessonTwoRenderer.mCubeColors, com.camera.control.renderer.LessonTwoRenderer.mCubeNormals, com.camera.control.renderer.LessonTwoRenderer.mCubePositions, com.camera.control.renderer.LessonTwoRenderer.mLightPosHandle, com.camera.control.renderer.LessonTwoRenderer.mLightPosInEyeSpace, com.camera.control.renderer.LessonTwoRenderer.mModelMatrix, com.camera.control.renderer.LessonTwoRenderer.mMVMatrixHandle, com.camera.control.renderer.LessonTwoRenderer.mMVPMatrix, com.camera.control.renderer.LessonTwoRenderer.mMVPMatrixHandle, com.camera.control.renderer.LessonTwoRenderer.mNormalDataSize, com.camera.control.renderer.LessonTwoRenderer.mNormalHandle, com.camera.control.renderer.LessonTwoRenderer.mPositionDataSize, com.camera.control.renderer.LessonTwoRenderer.mPositionHandle, com.camera.control.renderer.LessonTwoRenderer.mProjectionMatrix, com.camera.control.renderer.LessonTwoRenderer.mViewMatrix.
void com.camera.control.renderer.LessonTwoRenderer.drawLight()
Draws a point representing the position of the light.
References com.camera.control.renderer.LessonTwoRenderer.mLightModelMatrix, com.camera.control.renderer.LessonTwoRenderer.mLightPosInModelSpace, com.camera.control.renderer.LessonTwoRenderer.mMVPMatrix, com.camera.control.renderer.LessonTwoRenderer.mPointProgramHandle, com.camera.control.renderer.LessonTwoRenderer.mProjectionMatrix, com.camera.control.renderer.LessonTwoRenderer.mViewMatrix.
Referenced by com.camera.control.renderer.LessonTwoRenderer.onDrawFrame.
int com.camera.control.renderer.LessonTwoRenderer.compileShader(final int shaderType, final String shaderSource)
Helper function to compile a shader. shaderType The shader type. shaderSource The shader source code. An OpenGL handle to the shader.
References com.camera.control.renderer.LessonTwoRenderer.TAG.
Referenced by com.camera.control.renderer.LessonTwoRenderer.onSurfaceCreated.
int com.camera.control.renderer.LessonTwoRenderer.createAndLinkProgram(final int vertexShaderHandle, final int fragmentShaderHandle, final String[] attributes)
Helper function to compile and link a program. vertexShaderHandle An OpenGL handle to an already-compiled vertex shader. fragmentShaderHandle An OpenGL handle to an already-compiled fragment shader. attributes Attributes that need to be bound to the program. An OpenGL handle to the program.
References com.camera.control.renderer.LessonTwoRenderer.TAG.
Referenced by com.camera.control.renderer.LessonTwoRenderer.onSurfaceCreated.
final int com.camera.model.Light.mProgram
Referenced by com.camera.model.Light.draw, com.camera.model.Light.Light.
int com.camera.model.Light.mPositionHandle
Referenced by com.camera.model.Light.draw.
final String com.camera.model.Light.vertexShaderCode
Referenced by com.camera.model.Light.Light.
final String com.camera.model.Light.fragmentShaderCode
Referenced by com.camera.model.Light.Light.
FloatBuffer com.camera.model.Light.vertexBuffer
Referenced by com.camera.model.Light.draw, com.camera.model.Light.Light.
final int com.camera.model.Light.COORDS_PER_VERTEX
Referenced by com.camera.model.Light.draw.
float [] com.camera.model.Light.dotCoords
Referenced by com.camera.model.Light.Light.
float com.camera.model.Light.color[][]
com.camera.model.Light.Light()
References com.camera.model.Light.dotCoords, com.camera.model.Light.fragmentShaderCode, com.camera.model.Light.mProgram, com.camera.model.Light.vertexBuffer, com.camera.model.Light.vertexShaderCode.
void com.camera.model.Light.draw(float[] mvpMatrix)
References com.camera.model.Light.COORDS_PER_VERTEX, com.camera.model.Light.mPositionHandle, com.camera.model.Light.mProgram, com.camera.model.Light.vertexBuffer.
final int com.camera.view.activity.MainActivity.MEDIA_TYPE_IMAGE
Referenced by com.camera.view.activity.MainActivity.getOutputMediaFile.
final int com.camera.view.activity.MainActivity.MEDIA_TYPE_VIDEO
Referenced by com.camera.view.activity.MainActivity.getOutputMediaFile.
boolean com.camera.view.activity.MainActivity.capture
Referenced by com.camera.view.activity.MainActivity.onCreate, com.camera.control.renderer.MyGLRenderer.onDrawFrame.
int com.camera.view.activity.MainActivity.w
Referenced by com.camera.view.activity.MainActivity.onActivityResult, com.camera.control.renderer.MyGLRenderer.onDrawFrame.
int com.camera.view.activity.MainActivity.h
Referenced by com.camera.view.activity.MainActivity.onActivityResult, com.camera.control.renderer.MyGLRenderer.onDrawFrame.
Bitmap com.camera.view.activity.MainActivity.captureBmp
Referenced by com.camera.view.activity.MainActivity.onCreate.
final int com.camera.view.activity.MainActivity.CAPTURE_IMAGE_ACTIVITY_REQUEST_CODE
final int com.camera.view.activity.MainActivity.CAPTURE_VIDEO_ACTIVITY_REQUEST_CODE
final int com.camera.view.activity.MainActivity.IMAGE_SWITCHER_ACTIVITY_REQUEST_CODE
Referenced by com.camera.view.activity.MainActivity.onActivityResult, com.camera.view.activity.MainActivity.onCreate.
Uri com.camera.view.activity.MainActivity.fileUri
ImageView com.camera.view.activity.MainActivity.camer
Referenced by com.camera.view.activity.MainActivity.onCreate.
ImageView com.camera.view.activity.MainActivity.file
Referenced by com.camera.view.activity.MainActivity.onCreate.
ImageView com.camera.view.activity.MainActivity.loadModel
Referenced by com.camera.view.activity.MainActivity.onCreate.
ImageView com.camera.view.activity.MainActivity.translate
Referenced by com.camera.view.activity.MainActivity.onCreate.
ImageView com.camera.view.activity.MainActivity.rotate
Referenced by com.camera.view.activity.MainActivity.onCreate.
ImageView com.camera.view.activity.MainActivity.scale
Referenced by com.camera.view.activity.MainActivity.onCreate.
ImageView com.camera.view.activity.MainActivity.threeDiemension
Referenced by com.camera.view.activity.MainActivity.onCreate.
ImageView com.camera.view.activity.MainActivity.background
Referenced by com.camera.view.activity.MainActivity.onActivityResult, com.camera.view.activity.MainActivity.onCreate.
MyGLSurfaceView com.camera.view.activity.MainActivity.myGLSurfaceView
Referenced by com.camera.view.activity.MainActivity.onCreate.
Display com.camera.view.activity.MainActivity.display
Referenced by com.camera.view.activity.MainActivity.onCreate.
void com.camera.view.activity.MainActivity.onCreate(Bundle savedInstanceState)
References com.camera.view.activity.MainActivity.background, com.camera.view.activity.MainActivity.camer, com.camera.view.activity.MainActivity.capture, com.camera.view.activity.MainActivity.captureBmp, com.camera.view.activity.MainActivity.display, com.camera.view.activity.MainActivity.file, com.camera.utils.Util.getSavePath, com.camera.view.activity.MainActivity.IMAGE_SWITCHER_ACTIVITY_REQUEST_CODE, com.camera.view.activity.MainActivity.loadModel, com.camera.view.activity.MainActivity.myGLSurfaceView, com.camera.view.activity.MainActivity.rotate, com.camera.view.activity.MainActivity.scale, com.camera.view.activity.MainActivity.threeDiemension, com.camera.view.activity.MainActivity.translate.
void com.camera.view.activity.MainActivity.onActivityResult(int requestCode, int resultCode, Intent data)
References com.camera.view.activity.MainActivity.background, com.camera.view.activity.MainActivity.h, com.camera.view.activity.MainActivity.IMAGE_SWITCHER_ACTIVITY_REQUEST_CODE, com.camera.view.activity.ImageSwitcherAndGalleryActivity.SELECTED_PICTURE_PATH, com.camera.view.activity.MainActivity.w.
static Uri com.camera.view.activity.MainActivity.getOutputMediaFileUri(int type)
References com.camera.view.activity.MainActivity.getOutputMediaFile.
static File com.camera.view.activity.MainActivity.getOutputMediaFile(int type)
References com.camera.view.activity.MainActivity.MEDIA_TYPE_IMAGE, com.camera.view.activity.MainActivity.MEDIA_TYPE_VIDEO.
Referenced by com.camera.view.activity.MainActivity.getOutputMediaFileUri.
final int com.example.test.R.menu.main
final String com.camera.control.renderer.MyGLRenderer.TAG
Referenced by com.camera.control.renderer.MyGLRenderer.checkGlError.
List<Triangle> com.camera.control.renderer.MyGLRenderer.triangles
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame, com.camera.control.renderer.MyGLRenderer.parse.
final float [] com.camera.control.renderer.MyGLRenderer.mMVPMatrix
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame.
final float [] com.camera.control.renderer.MyGLRenderer.mProjectionMatrix
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame, com.camera.control.renderer.MyGLRenderer.onSurfaceChanged.
final float [] com.camera.control.renderer.MyGLRenderer.mViewMatrix
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame.
final float [] com.camera.control.renderer.MyGLRenderer.mRotationMatrix
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame.
float [] com.camera.control.renderer.MyGLRenderer.scaleMatrix
float com.camera.control.renderer.MyGLRenderer.mAngle
Referenced by com.camera.control.renderer.MyGLRenderer.getAngle, com.camera.control.renderer.MyGLRenderer.onDrawFrame, com.camera.control.renderer.MyGLRenderer.setAngle.
String com.camera.control.renderer.MyGLRenderer.modelPath
Referenced by com.camera.control.renderer.MyGLRenderer.parse, com.camera.control.renderer.MyGLRenderer.setModelPath.
float com.camera.control.renderer.MyGLRenderer.scaleRatio
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame, com.camera.control.renderer.MyGLRenderer.setScaleRatio.
float com.camera.control.renderer.MyGLRenderer.minX
Referenced by com.camera.control.renderer.MyGLRenderer.getScaleMatrix, com.camera.control.renderer.MyGLRenderer.parse.
float com.camera.control.renderer.MyGLRenderer.maxX
Referenced by com.camera.control.renderer.MyGLRenderer.getScaleMatrix, com.camera.control.renderer.MyGLRenderer.parse.
float com.camera.control.renderer.MyGLRenderer.minY
Referenced by com.camera.control.renderer.MyGLRenderer.getScaleMatrix, com.camera.control.renderer.MyGLRenderer.parse.
float com.camera.control.renderer.MyGLRenderer.maxY
Referenced by com.camera.control.renderer.MyGLRenderer.getScaleMatrix, com.camera.control.renderer.MyGLRenderer.parse.
float com.camera.control.renderer.MyGLRenderer.minZ
Referenced by com.camera.control.renderer.MyGLRenderer.getScaleMatrix, com.camera.control.renderer.MyGLRenderer.parse.
float com.camera.control.renderer.MyGLRenderer.maxZ
Referenced by com.camera.control.renderer.MyGLRenderer.getScaleMatrix, com.camera.control.renderer.MyGLRenderer.parse.
boolean com.camera.control.renderer.MyGLRenderer.initialized
Referenced by com.camera.control.renderer.MyGLRenderer.parse.
float com.camera.control.renderer.MyGLRenderer.translateX
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame, com.camera.control.renderer.MyGLRenderer.setTranslate.
float com.camera.control.renderer.MyGLRenderer.translateY
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame, com.camera.control.renderer.MyGLRenderer.setTranslate.
float com.camera.control.renderer.MyGLRenderer.translateZ
Referenced by com.camera.control.renderer.MyGLRenderer.onDrawFrame, com.camera.control.renderer.MyGLRenderer.setTranslate.
void com.camera.control.renderer.MyGLRenderer.onSurfaceCreated(GL10 unused, EGLConfig config)
References com.camera.control.renderer.MyGLRenderer.parse.
void com.camera.control.renderer.MyGLRenderer.onDrawFrame(GL10 gl)
References com.camera.view.activity.MainActivity.capture, com.camera.view.activity.MainActivity.h, com.camera.control.renderer.MyGLRenderer.mAngle, com.camera.control.renderer.MyGLRenderer.mMVPMatrix, com.camera.control.renderer.MyGLRenderer.mProjectionMatrix, com.camera.control.renderer.MyGLRenderer.mRotationMatrix, com.camera.control.renderer.MyGLRenderer.mViewMatrix, com.camera.control.renderer.MyGLRenderer.scaleRatio, com.camera.control.renderer.MyGLRenderer.translateX, com.camera.control.renderer.MyGLRenderer.translateY, com.camera.control.renderer.MyGLRenderer.translateZ, com.camera.control.renderer.MyGLRenderer.triangles, com.camera.view.activity.MainActivity.w.
void com.camera.control.renderer.MyGLRenderer.onSurfaceChanged(GL10 unused, int width, int height)
References com.camera.control.renderer.MyGLRenderer.mProjectionMatrix.
float com.camera.control.renderer.MyGLRenderer.getAngle()
Returns the rotation angle of the triangle shape (mTriangle).- A float representing the rotation angle.
References com.camera.control.renderer.MyGLRenderer.mAngle.
void com.camera.control.renderer.MyGLRenderer.setAngle(float angle)
Sets the rotation angle of the triangle shape (mTriangle).
References com.camera.control.renderer.MyGLRenderer.mAngle.
void com.camera.control.renderer.MyGLRenderer.setScaleRatio(float ratio)
Sets the scale ratio of the triangle shape (mTriangle).
References com.camera.control.renderer.MyGLRenderer.scaleRatio.
void com.camera.control.renderer.MyGLRenderer.setTranslate(float x, float y)
Sets the translate position of the triangle shape(mTriangle).
References com.camera.control.renderer.MyGLRenderer.translateX, com.camera.control.renderer.MyGLRenderer.translateY, com.camera.control.renderer.MyGLRenderer.translateZ.
void com.camera.control.renderer.MyGLRenderer.setModelPath(String path)
References com.camera.control.renderer.MyGLRenderer.modelPath.
static int com.camera.control.renderer.MyGLRenderer.loadShader(int type, String shaderCode)
Utility method for compiling a OpenGL shader.Note: When developing shaders, use the checkGlError() method to debug shader coding errors. type Vertex or fragment shader type. shaderCode String containing the shader code. - Returns an id for the shader.
static void com.camera.control.renderer.MyGLRenderer.checkGlError(String glOperation)
Utility method for debugging OpenGL calls. Provide the name of the call just after making it: mColorHandle = GLES20.glGetUniformLocation(mProgram, "vColor"); MyGLRenderer.checkGlError("glGetUniformLocation"); If the operation is not successful, the check throws an error. glOperation Name of the OpenGL call to check.
References com.camera.control.renderer.MyGLRenderer.TAG.
void com.camera.control.renderer.MyGLRenderer.parse()
References com.camera.control.renderer.MyGLRenderer.getScaleMatrix, com.camera.control.renderer.MyGLRenderer.initialized, com.camera.control.renderer.MyGLRenderer.maxX, com.camera.control.renderer.MyGLRenderer.maxY, com.camera.control.renderer.MyGLRenderer.maxZ, com.camera.control.renderer.MyGLRenderer.minX, com.camera.control.renderer.MyGLRenderer.minY, com.camera.control.renderer.MyGLRenderer.minZ, com.camera.control.renderer.MyGLRenderer.modelPath, com.camera.control.renderer.MyGLRenderer.triangles.
Referenced by com.camera.control.renderer.MyGLRenderer.onSurfaceCreated.
void com.camera.control.renderer.MyGLRenderer.getScaleMatrix()
References com.camera.control.renderer.MyGLRenderer.maxX, com.camera.control.renderer.MyGLRenderer.maxY, com.camera.control.renderer.MyGLRenderer.maxZ, com.camera.control.renderer.MyGLRenderer.minX, com.camera.control.renderer.MyGLRenderer.minY, com.camera.control.renderer.MyGLRenderer.minZ.
Referenced by com.camera.control.renderer.MyGLRenderer.parse.
final String com.camera.view.MyGLSurfaceView.TAG
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent.
final MyGLRenderer com.camera.view.MyGLSurfaceView.mRenderer
Referenced by com.camera.view.MyGLSurfaceView.MyGLSurfaceView.
final float com.camera.view.MyGLSurfaceView.TOUCH_SCALE_FACTOR
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent.
float com.camera.view.MyGLSurfaceView.mPreviousX
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent.
float com.camera.view.MyGLSurfaceView.mPreviousY
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent.
boolean com.camera.view.MyGLSurfaceView.translateFlag
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent, com.camera.view.MyGLSurfaceView.setRotateFlag, com.camera.view.MyGLSurfaceView.setScaleFlag, com.camera.view.MyGLSurfaceView.setTranslateFlag.
boolean com.camera.view.MyGLSurfaceView.scaleFlag
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent, com.camera.view.MyGLSurfaceView.setRotateFlag, com.camera.view.MyGLSurfaceView.setScaleFlag, com.camera.view.MyGLSurfaceView.setTranslateFlag.
boolean com.camera.view.MyGLSurfaceView.rotateFlag
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent, com.camera.view.MyGLSurfaceView.setRotateFlag, com.camera.view.MyGLSurfaceView.setScaleFlag, com.camera.view.MyGLSurfaceView.setTranslateFlag.
int com.camera.view.MyGLSurfaceView.mode
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent.
float com.camera.view.MyGLSurfaceView.previousDistance
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent.
com.camera.view.MyGLSurfaceView.MyGLSurfaceView(Context context)
References com.camera.view.MyGLSurfaceView.mRenderer.
com.camera.view.MyGLSurfaceView.MyGLSurfaceView(Context context, AttributeSet attrs)
References com.camera.view.MyGLSurfaceView.mRenderer.
boolean com.camera.view.MyGLSurfaceView.onTouchEvent(MotionEvent e)
References com.camera.view.MyGLSurfaceView.mode, com.camera.view.MyGLSurfaceView.mPreviousX, com.camera.view.MyGLSurfaceView.mPreviousY, com.camera.view.MyGLSurfaceView.previousDistance, com.camera.view.MyGLSurfaceView.rotateFlag, com.camera.view.MyGLSurfaceView.scaleFlag, com.camera.view.MyGLSurfaceView.spacing, com.camera.view.MyGLSurfaceView.TAG, com.camera.view.MyGLSurfaceView.TOUCH_SCALE_FACTOR, com.camera.view.MyGLSurfaceView.translateFlag.
void com.camera.view.MyGLSurfaceView.setTranslateFlag()
References com.camera.view.MyGLSurfaceView.rotateFlag, com.camera.view.MyGLSurfaceView.scaleFlag, com.camera.view.MyGLSurfaceView.translateFlag.
void com.camera.view.MyGLSurfaceView.setScaleFlag()
References com.camera.view.MyGLSurfaceView.rotateFlag, com.camera.view.MyGLSurfaceView.scaleFlag, com.camera.view.MyGLSurfaceView.translateFlag.
void com.camera.view.MyGLSurfaceView.setRotateFlag()
References com.camera.view.MyGLSurfaceView.rotateFlag, com.camera.view.MyGLSurfaceView.scaleFlag, com.camera.view.MyGLSurfaceView.translateFlag.
boolean com.camera.view.MyGLSurfaceView.getTranslateFlag()
boolean com.camera.view.MyGLSurfaceView.getScaleFlag()
boolean com.camera.view.MyGLSurfaceView.getRotateFlag()
float com.camera.view.MyGLSurfaceView.spacing(MotionEvent event)
Referenced by com.camera.view.MyGLSurfaceView.onTouchEvent.
View com.camera.control.loader.ObjLoader.loadObj(String filePath)
GLSurfaceView com.camera.view.activity.OpenGLES20Activity.mGLView
Referenced by com.camera.view.activity.OpenGLES20Activity.onCreate.
void com.camera.view.activity.OpenGLES20Activity.onCreate(Bundle savedInstanceState)
References com.camera.view.activity.OpenGLES20Activity.mGLView.
void com.camera.view.activity.OpenGLES20Activity.onPause()
void com.camera.view.activity.OpenGLES20Activity.onResume()
final String com.camera.view.activity.PaperDetectionActivity.TAG
MenuItem com.camera.view.activity.PaperDetectionActivity.saveImage
Referenced by com.camera.view.activity.PaperDetectionActivity.onCreateOptionsMenu, com.camera.view.activity.PaperDetectionActivity.onMenuItemSelected.
final int com.camera.view.activity.PaperDetectionActivity.ACCUMULATOR_THRESHOLD
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame.
final int com.camera.view.activity.PaperDetectionActivity.MINLINELENGTH
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame.
final int com.camera.view.activity.PaperDetectionActivity.MAXLINEGAP
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame.
final int com.camera.view.activity.PaperDetectionActivity.HYSTERESIS_THRESHOLD1
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame.
final int com.camera.view.activity.PaperDetectionActivity.HYSTERESIS_THRESHOLD2
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame.
final int com.camera.view.activity.PaperDetectionActivity.HOUGH_LINE_COUNT
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame.
Mat com.camera.view.activity.PaperDetectionActivity.mRgba
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame, com.camera.view.activity.PaperDetectionActivity.onCameraViewStarted, com.camera.view.activity.PaperDetectionActivity.onMenuItemSelected.
Mat com.camera.view.activity.PaperDetectionActivity.mGray
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame.
Mat com.camera.view.activity.PaperDetectionActivity.lines
Referenced by com.camera.view.activity.PaperDetectionActivity.onCameraFrame, com.camera.view.activity.PaperDetectionActivity.onCameraViewStarted.
Tutorial3View com.camera.view.activity.PaperDetectionActivity.mOpenCvCameraView
Referenced by com.camera.view.activity.PaperDetectionActivity.onCreate, com.camera.view.activity.PaperDetectionActivity.onDestroy, com.camera.view.activity.PaperDetectionActivity.onPause.
BaseLoaderCallback com.camera.view.activity.PaperDetectionActivity.mLoaderCallback
Referenced by com.camera.view.activity.PaperDetectionActivity.onResume.
void com.camera.view.activity.PaperDetectionActivity.onCreate(Bundle savedInstanceState)
References com.camera.view.activity.PaperDetectionActivity.mOpenCvCameraView.
void com.camera.view.activity.PaperDetectionActivity.onResume()
References com.camera.view.activity.PaperDetectionActivity.mLoaderCallback.
void com.camera.view.activity.PaperDetectionActivity.onPause()
References com.camera.view.activity.PaperDetectionActivity.mOpenCvCameraView.
void com.camera.view.activity.PaperDetectionActivity.onDestroy()
References com.camera.view.activity.PaperDetectionActivity.mOpenCvCameraView.
void com.camera.view.activity.PaperDetectionActivity.onCameraViewStarted(int width, int height)
References com.camera.view.activity.PaperDetectionActivity.lines, com.camera.view.activity.PaperDetectionActivity.mRgba.
void com.camera.view.activity.PaperDetectionActivity.onCameraViewStopped()
Mat com.camera.view.activity.PaperDetectionActivity.onCameraFrame(CvCameraViewFrame inputFrame)
References com.camera.view.activity.PaperDetectionActivity.ACCUMULATOR_THRESHOLD, com.camera.view.activity.PaperDetectionActivity.HOUGH_LINE_COUNT, com.camera.view.activity.PaperDetectionActivity.HYSTERESIS_THRESHOLD1, com.camera.view.activity.PaperDetectionActivity.HYSTERESIS_THRESHOLD2, com.camera.view.activity.PaperDetectionActivity.lines, com.camera.view.activity.PaperDetectionActivity.MAXLINEGAP, com.camera.view.activity.PaperDetectionActivity.mGray, com.camera.view.activity.PaperDetectionActivity.MINLINELENGTH, com.camera.view.activity.PaperDetectionActivity.mRgba.
boolean com.camera.view.activity.PaperDetectionActivity.onMenuItemSelected(int featureId, MenuItem item)
References com.camera.view.activity.PaperDetectionActivity.mRgba, com.camera.view.activity.PaperDetectionActivity.saveImage.
boolean com.camera.view.activity.PaperDetectionActivity.onCreateOptionsMenu(Menu menu)
References com.camera.view.activity.PaperDetectionActivity.saveImage.
boolean com.camera.view.activity.PaperDetectionActivity.onTouch(View v, MotionEvent event)
final String com.camera.model.Square.vertexShaderCode
Referenced by com.camera.model.Square.Square.
final String com.camera.model.Square.fragmentShaderCode
Referenced by com.camera.model.Square.Square.
final FloatBuffer com.camera.model.Square.vertexBuffer
Referenced by com.camera.model.Square.draw, com.camera.model.Square.Square.
final ShortBuffer com.camera.model.Square.drawListBuffer
Referenced by com.camera.model.Square.draw, com.camera.model.Square.Square.
final int com.camera.model.Square.mProgram
Referenced by com.camera.model.Square.draw, com.camera.model.Square.Square.
int com.camera.model.Square.mPositionHandle
Referenced by com.camera.model.Square.draw.
int com.camera.model.Square.mColorHandle
Referenced by com.camera.model.Square.draw.
int com.camera.model.Square.mMVPMatrixHandle
Referenced by com.camera.model.Square.draw.
final short com.camera.model.Square.drawOrder[][]
Referenced by com.camera.model.Square.Square.
final int com.camera.model.Square.vertexStride
Referenced by com.camera.model.Square.draw.
final int com.camera.model.Square.COORDS_PER_VERTEX
Referenced by com.camera.model.Square.draw.
float com.camera.model.Square.squareCoords[][]
Referenced by com.camera.model.Square.Square.
float com.camera.model.Square.color[][]
Referenced by com.camera.model.Square.draw.
com.camera.model.Square.Square()
Sets up the drawing object data for use in an OpenGL ES context.
References com.camera.model.Square.drawListBuffer, com.camera.model.Square.drawOrder, com.camera.model.Square.fragmentShaderCode, com.camera.model.Square.mProgram, com.camera.model.Square.squareCoords, com.camera.model.Square.vertexBuffer, com.camera.model.Square.vertexShaderCode.
void com.camera.model.Square.draw(float[] mvpMatrix)
Encapsulates the OpenGL ES instructions for drawing this shape. mvpMatrix - The Model View Project matrix in which to draw this shape.
References com.camera.model.Square.color, com.camera.model.Square.COORDS_PER_VERTEX, com.camera.model.Square.drawListBuffer, com.camera.model.Square.mColorHandle, com.camera.model.Square.mMVPMatrixHandle, com.camera.model.Square.mPositionHandle, com.camera.model.Square.mProgram, com.camera.model.Square.vertexBuffer, com.camera.model.Square.vertexStride.
final int com.example.test.R.string.action_settings
final int com.example.test.R.string.app_name
final int com.example.test.R.string.hello_world
final int com.example.test.R.style.AppBaseTheme
Base application theme for API 11+. This theme completely replaces AppBaseTheme from res/values/styles.xml on API 11+ devices.API 11 theme customizations can go here. Base application theme for API 14+. This theme completely replaces AppBaseTheme from BOTH res/values/styles.xml and res/values-v11/styles.xml on API 14+ devices. API 14 theme customizations can go here.
final int [] com.example.test.R.styleable.Gallery
Attributes that can be used with a Gallery. Includes the following attributes: <colgroup align="left"> AttributeDescription android:galleryItemBackgroundGallery_android_galleryItemBackground
final int com.example.test.R.styleable.Gallery_android_galleryItemBackground
This symbol is the offset where the android.R.attr#galleryItemBackground attribute's value can be found in the Gallery array. name android:galleryItemBackground
final int [] org.opencv.R.styleable.CameraBridgeViewBase
final int org.opencv.R.styleable.CameraBridgeViewBase_camera_id
final int org.opencv.R.styleable.CameraBridgeViewBase_show_fps
final String com.camera.model.Triangle.vertexShaderCode
Referenced by com.camera.model.Triangle.Triangle.
final String com.camera.model.Triangle.fragmentShaderCode
Referenced by com.camera.model.Triangle.Triangle.
final FloatBuffer com.camera.model.Triangle.vertexBuffer
Referenced by com.camera.model.Triangle.draw, com.camera.model.Triangle.Triangle.
final int com.camera.model.Triangle.mProgram
Referenced by com.camera.model.Triangle.draw, com.camera.model.Triangle.Triangle.
int com.camera.model.Triangle.mPositionHandle
Referenced by com.camera.model.Triangle.draw.
int com.camera.model.Triangle.mColorHandle
Referenced by com.camera.model.Triangle.draw.
int com.camera.model.Triangle.mMVPMatrixHandle
Referenced by com.camera.model.Triangle.draw.
final int com.camera.model.Triangle.vertexCount
Referenced by com.camera.model.Triangle.draw.
final int com.camera.model.Triangle.vertexStride
Referenced by com.camera.model.Triangle.draw.
final int com.camera.model.Triangle.COORDS_PER_VERTEX
Referenced by com.camera.model.Triangle.draw.
float com.camera.model.Triangle.triangleCoords[][]
Referenced by com.camera.model.Triangle.Triangle.
float com.camera.model.Triangle.color[][]
Referenced by com.camera.model.Triangle.draw.
com.camera.model.Triangle.Triangle()
Sets up the drawing object data for use in an OpenGL ES context.
References com.camera.model.Triangle.fragmentShaderCode, com.camera.model.Triangle.mProgram, com.camera.model.Triangle.triangleCoords, com.camera.model.Triangle.vertexBuffer, com.camera.model.Triangle.vertexShaderCode.
com.camera.model.Triangle.Triangle(float[] vertexs)
References com.camera.model.Triangle.fragmentShaderCode, com.camera.model.Triangle.mProgram, com.camera.model.Triangle.vertexBuffer, com.camera.model.Triangle.vertexShaderCode.
void com.camera.model.Triangle.draw(float[] mvpMatrix)
Encapsulates the OpenGL ES instructions for drawing this shape. mvpMatrix The Model View Project matrix in which to draw this shape.
References com.camera.model.Triangle.color, com.camera.model.Triangle.COORDS_PER_VERTEX, com.camera.model.Triangle.mColorHandle, com.camera.model.Triangle.mMVPMatrixHandle, com.camera.model.Triangle.mPositionHandle, com.camera.model.Triangle.mProgram, com.camera.model.Triangle.vertexBuffer, com.camera.model.Triangle.vertexCount, com.camera.model.Triangle.vertexStride.
final String com.camera.view.Tutorial3View.TAG
Referenced by com.camera.view.Tutorial3View.onPictureTaken, com.camera.view.Tutorial3View.takePicture.
String com.camera.view.Tutorial3View.mPictureFileName
Referenced by com.camera.view.Tutorial3View.onPictureTaken.
com.camera.view.Tutorial3View.Tutorial3View(Context context, AttributeSet attrs)
List<String> com.camera.view.Tutorial3View.getEffectList()
boolean com.camera.view.Tutorial3View.isEffectSupported()
String com.camera.view.Tutorial3View.getEffect()
void com.camera.view.Tutorial3View.setEffect(String effect)
List<Size> com.camera.view.Tutorial3View.getResolutionList()
void com.camera.view.Tutorial3View.setResolution(Size resolution)
Size com.camera.view.Tutorial3View.getResolution()
void com.camera.view.Tutorial3View.takePicture(final String fileName)
References com.camera.view.Tutorial3View.TAG.
void com.camera.view.Tutorial3View.onPictureTaken(byte[] data, Camera camera)
References com.camera.view.Tutorial3View.mPictureFileName, com.camera.view.Tutorial3View.TAG.